Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # Load Balancer
  config.vm.define "k8s-loadbalancer" do |lb|
    lb.vm.hostname = "k8s-loadbalancer"
    lb.vm.network "private_network", ip: "192.168.56.10"
    lb.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end

  # Masters
  (1..3).each do |i|
    config.vm.define "k8s-master-#{i}" do |master|
      master.vm.hostname = "k8s-master-#{i}"
      master.vm.network "private_network", ip: "192.168.56.#{10 + i}"
      master.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = 2
      end
    end
  end

  # Workers
  (1..2).each do |i|
    config.vm.define "k8s-worker-#{i}" do |worker|
      worker.vm.hostname = "k8s-worker-#{i}"
      worker.vm.network "private_network", ip: "192.168.56.#{20 + i}"
      worker.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = 2
      end
    end
  end
end